### ISSUE TITLE
Publication preview image zoom does not work on Safari

### ISSUE THREAD

**Issue by jiuntian** [alshedivat/al-folio#3069]
### Have you checked that your issue isn't already filed?

- [x] I read through [FAQ](https://github.com/alshedivat/al-folio/blob/main/FAQ.md) and searched through the [past issues](https://github.com/alshedivat/al-folio/issues), none of which addressed my issue.
- [x] Yes, I have checked that this issue isn't already filed.

### Bug description

Publication preview thumbnails are enlarged but displayed at blurred upon mouse click.

### How to reproduce the bug

1. On Safari, go to any publication entry with a preview image which originally is of larger size than the thumbnail. (e.g. [my website](https://www.jiuntian.com))
2. Click on the thumbnail to zoom in.
3. The image is enlarged but still displayed blurred.

Tested with Safari 18.3 on macOS and Safari 18.3 on iOS (landscape mode so that the preview image is in thumbnail mode)

### Error messages and logs

```
The error message you got, with the full traceback if available. Please paste it between these triple backticks.
```

### What operating system are you using?

Mac

### Where are you seeing the problem on?

Deployed site

### More info

I am on latest commit of main branch (afc34968a7d2e82e66438b58faaeb3bdc1beafbf), which also includes #2668 that solved the problem preview image not enlarged.

**Comment by george-gca** [comment]
Can you help with this @pourmand1376? I don't have safari.

**Comment by pourmand1376** [comment]
Hey, Thanks for reporting the bug. 

I couldn't see the bug myself. Could you provide more information on how it happens? Does it happen with main template or is it your customizations?

I went to [this](http://localhost:8080/al-folio/publications/) url on my al-folio template and it has no problem.

**Comment by jiuntian** [comment]
Here are more details to reproduce this:

1. use a large image as publication preview
2. go to publication page
3. click on the publication preview thumbnail to enlarge it
4. you should see a blurry enlarged version of 

I think it not just happened to me, as what I found, the example website mentioned in #2668 also have same problem, you can reproduce this on [his site](https://wangyi.fan/publications/). I think I have no customization, at least not on the liquid part.

Thank for your attention.

**Comment by bjbraun** [comment]
It is the same for my website (https://bjbraun.github.io). On Chrome, the publication preview shows in high resolution but on Safari it does not work.

 I have also implemented https://github.com/alshedivat/al-folio/issues/2668 just recently.

**Comment by george-gca** [comment]
Can you try just in case in an anonymous tab in safari? I think it does have this, right?

**Comment by jiuntian** [comment]
Hi @george-gca , I tried on new private window, equivalent to anonymous tab. I can confirm the problem persists.

<img width="1017" alt="Image" src="https://github.com/user-attachments/assets/e80f31ec-836d-4454-88e3-5da87e95df87" />

**Comment by george-gca** [comment]
Can you check which image is being loaded? What is the name and extension of the image shown, both in chrome and safari?

**Comment by george-gca** [comment]
I mean it like this:

![Image](https://github.com/user-attachments/assets/95a2167c-77b8-43ab-85c1-f2763d6eb5c0)

select the image and check its `src`. In my case, it is displaying a `png` image, not a `webp`. Check if the same happens for you: https://www.jiuntian.com/publications/

**Comment by pourmand1376** [comment]
![Image](https://github.com/user-attachments/assets/03fe8caa-f9be-4e4f-8bb7-b0f374613f67)

It is a png image.

**Comment by pourmand1376** [comment]
I found multiple solutions on the internet. None of them worked.

**Comment by george-gca** [comment]
It doesn't make any sense. I was "hoping" that, for some unknown reason, safari was displaying the webp image instead of the png. Can you verify if the images [here](https://medium-zoom.francoischalifour.com/) are displayed blurred? This is the demo site for the [library](https://github.com/francoischalifour/medium-zoom) that we use to do the zoom feature.

**Comment by jiuntian** [comment]
I can trigger the problem. I think it might be related to how safari handle images of smaller size, which they resize the image. It is not that blurry if the image is large enough, like at least 300px, though there's still some pixelated due to resizing.

Here are the step to reproduce:
1. Select the image, and change its width, so that it become very small.
2. For example, in here I changed the `pull-right` class to width of 100px, which is small enough.
3. Then the image is automatically reduced in resolution, and becomes blurry when zoomed.

![Image](https://github.com/user-attachments/assets/c39552e6-1c3f-49e2-b2c5-2a8303caf900)

![Image](https://github.com/user-attachments/assets/fb9a910f-7c4b-4221-8fe8-38f625b1eecd)

**Comment by george-gca** [comment]
Does this work as supposed on chrome?

**Comment by jiuntian** [comment]
It works as supposed on chrome. When click to zoom the image, it will reload the image.

**Comment by george-gca** [comment]
I don't know how easy or not it is to fix it. Try opening an issue in the [medium-zoom](https://github.com/francoischalifour/medium-zoom) repository.

**Comment by jiuntian** [comment]
Maybe related to this, but it seems it remains unresolved for many years.

https://github.com/francoischalifour/medium-zoom/issues/151

**Comment by maxhaice2** [comment]
I guess this is because of how WebKit renders transforms when hardware acceleration is enabled (like in iPhone). It increases performance but affects antialiasing when you apply a 3DTransform when no fundamental transformation happens...
Try to remove 'translate3d' or make it optional to optimize/savequality
